### ISSUE TITLE
Membership is expired while subscription is showing as active.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#101]
WordPress version: 5.8.1
WooCommerce version: 5.8.0
Area Path: Store-> My account-> Membership Details
Version: 2.0.0
Description: Membership is expired while subscription is showing as active. Also, it is not taking the correct price of the membership plan.
![Screenshot (92)](https://user-images.githubusercontent.com/76723329/138998445-fc4b50ee-bcfb-4958-aba2-1b320131372b.png)
![Screenshot(10)](https://user-images.githubusercontent.com/76723329/138998468-ec2d54e8-179c-4514-bdda-6128bee22f62.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left. The membership plan is getting expired before time while the subscription is still active.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
