### ISSUE TITLE
Membership Under Review status is not coming on product single page.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#102]
WordPress version: 5.8.1
WooCommerce version: 5.8.0
Area Path: Shop
Version: 2.0.0
Description: Membership Under Review status is not coming on the product single page.
![Screenshot - 2021-10-30T160840 542](https://user-images.githubusercontent.com/76723329/139529599-ecddaf10-1142-4598-acda-6a514cd53d3a.png)
![Screenshot - 2021-10-30T160908 956](https://user-images.githubusercontent.com/76723329/139529604-331d73ff-294a-45eb-b006-954b75b495ca.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
