### ISSUE TITLE
Enabling Memberships from multi step form it is not showing in settings as enabled.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#103]
WordPress version: 5.8.2
WooCommerce version: 5.9
Area Path: Adminpanel-> MakeWebBetter
Version: 2.0.1
Description: Enabling/ Disabling Memberships from the multi-step form is not coming correctly in settings after completing form.
![Screenshot (57)](https://user-images.githubusercontent.com/76723329/144046097-3f87460e-ea5d-417f-a93b-deeb6de96569.png)
![Screenshot (56)](https://user-images.githubusercontent.com/76723329/144046131-58215bda-4c85-40f3-b3e3-0e436a89bce5.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
