### ISSUE TITLE
Add New member is not working fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#104]
WordPress version: 5.8.1
WooCommerce version: 5.8.0
Area Path: Admin panel-> Memberships-> All Members
Version: 2.0.0
Description: Add New member is not working fine. As of now, users other than admin can't be assigned to membership. Also content needs to be updated.
![Screenshot - 2021-10-30T171634 851](https://user-images.githubusercontent.com/76723329/139531651-9aa1907e-f639-48f3-b95a-c73e4806034b.png)
![Screenshot - 2021-10-30T171310 520](https://user-images.githubusercontent.com/76723329/139531659-77728dc5-fac4-4ac1-88cb-1b14cb5f45b7.png)
![Screenshot - 2021-10-30T171151 240](https://user-images.githubusercontent.com/76723329/139531663-3e60e2a6-5114-4c5b-9233-5c95af3ff913.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still needs modifications as per compatibility with subscriptions.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
