### ISSUE TITLE
Issues in Membership plan duration & subscription expiry.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#105]
WordPress version: 5.8.1
WooCommerce version: 5.8.0
Area Path: Admin panel-> Memberships-> All Membership Plans
Version: 2.0.0
Description: Issues in Membership plan duration & subscription expiry. Also issues in Membership plans page
![Screenshot - 2021-10-30T174705 052](https://user-images.githubusercontent.com/76723329/139532648-496b96c9-f385-47f4-b337-507c8b032022.png)
![Screenshot - 2021-10-30T174822 657](https://user-images.githubusercontent.com/76723329/139532653-4268bb79-5632-4b07-afc7-64341c3630dc.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
