### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#106]
**Plugin: Membership For WooCommerce**
**Version: 2.0.0**

**Language issues:**
[ORGlog.txt](https://github.com/Makewebbetter/membership-for-woocommerce/files/7467146/ORGlog.txt)
![Screenshot from 2021-11-03 16-50-11](https://user-images.githubusercontent.com/76723329/140051482-24058389-cbec-410d-ad51-13b3cc723ae4.png)

**Grammatical issues:**
#: admin/partials/templates/membership-templates/mwb-membership-plans-creation.php:529
msgid "Select the products you want to included in Membership Plan."
msgstr ""
--> "Select the products you want to include in Membership Plan."

#: admin/partials/templates/membership-templates/mwb-membership-plans-creation.php:621
msgid "Select the tags you want to included in Membership Plan."
msgstr ""
--> "Select the tags you want to include in Membership Plan."

#: admin/partials/templates/membership-templates/mwb-membership-plans-creation.php:668
msgid "Select the posts you want to included in Membership Plan."
msgstr ""
--> "Select the posts you want to include in Membership Plan."

#: admin/partials/templates/membership-templates/mwb-membership-plans-creation.php:716
msgid "Select the post categories you want to included in Membership Plan."
msgstr ""
--> "Select the post categories you want to include in Membership Plan."

#: admin/partials/templates/membership-templates/mwb-membership-plans-creation.php:763
msgid "Select the post tags you want to included in Membership Plan."
msgstr ""
--> "Select the post tags you want to include in Membership Plan."

#: admin/partials/templates/membership-templates/mwb-membership-shortcodes.php:57
msgid ""
"This shortcode only returns no thanks button. Use it as [mwb_membership_no]."
msgstr ""
--> "This shortcode only returns the no thanks button. Use it as [mwb_membership_no]."

#: src/component/FinalStep.js:61
msgid ""
"Bingo! You are all set to take advantage of your business. Lastly, we urge "
"you to allow us collect some"
msgstr ""
--> "you to allow us to collect some"

**Comment by Ananya-Cedcoss** [comment]
can't be fixed as i checked

**Comment by ChiragGupta-CEDCOSS** [comment]
Fine for now.
