### ISSUE TITLE
Settings are available to create plan while Multi step form is not filled.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#107]
WordPress version: 5.8.2
WooCommerce version: 5.9
Area Path: Admin panel-> Memberships-> All Membership Plans
Version: 2.0.1
Description: Settings should be available to create plan after Multi step form is filled.
![Membership For W](https://user-images.githubusercontent.com/76723329/144045078-c8c30ce3-1b33-4a07-ba23-8f9637936be5.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
