### ISSUE TITLE
Login details are not getting sent to guest user after purchasing membership plan.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#109]
WordPress version: 5.8.2
WooCommerce version: 5.9
Area Path: Admin panel-> Users-> All Users
Version: 2.0.1
Description: Login details are not getting sent to the guest users to log in after purchasing the membership plan. Also when the **Create User after payment done** setting is enabled the account is getting created without user details.
![Screenshot (59)](https://user-images.githubusercontent.com/76723329/144071146-dc541651-013a-4548-a9d6-dbf229877dc7.png)
![Screenshot (60)](https://user-images.githubusercontent.com/76723329/144072203-56ad54ac-cf29-4b71-a6f8-429d26dda8a9.png)
![Screenshot (61)](https://user-images.githubusercontent.com/76723329/144074126-b95227f0-1d71-4fe1-bd79-85d3bd71f1d2.png)
![Screenshot (62)](https://user-images.githubusercontent.com/76723329/144074273-dd261c11-9700-4ec1-9bf0-2883362c71d2.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.
![Screenshot (61)](https://user-images.githubusercontent.com/76723329/144550484-164075f7-2c52-4732-b278-7b46a79e53a6.png)

![Screenshot (78)](https://user-images.githubusercontent.com/76723329/144550429-ee0f809f-99a0-4fb4-a4cd-cc122fd73b1e.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
