### ISSUE TITLE
Issue coming when membership is Under Review.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#110]
WordPress version: 5.8.2
WooCommerce version: 5.9
Area Path: Store
Version: 2.0.1
Description: Issue coming when membership is Under Review.
![screenshot-membership-testing local-2021-12-01-09-36-35-994](https://user-images.githubusercontent.com/76723329/144172228-ac6f8927-735d-4b89-9083-1f8336d414e5.png)
![Screenshot (63)](https://user-images.githubusercontent.com/76723329/144172248-ac8d4349-c432-4ab6-8fde-401987f8f59d.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
