### ISSUE TITLE
Activation - Deactivation Data not received.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/membership-for-woocommerce#123]
**Bug Name -** Activation - Deactivation Data not received.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.1.1
**WordPress Version -** 5.8.2
**Plugin Version -** 
**Description -**

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
