### ISSUE TITLE
The message "Membership plan published successfully, Now you can manage membership free shipping" is appearing everytime when we update plan.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#14]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Admin Panel --> Plans --> All Plans --> Add Plans
Status: new
Version: 1.0.0
Description: The message **Membership plan published successfully, Now you can manage membership free shipping** is appearing everytime when admin updates the plan post. this message should come only first time when new plan is created, for updation there should be another message.
![Edit-Plan-‹-Membership-for-WooCommerce-—-WordPress (4)](https://user-images.githubusercontent.com/76723329/109482834-82a4dd80-7aa4-11eb-9093-44fb41d8a26f.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
The message coming again.
![Screenshot (88)](https://user-images.githubusercontent.com/76723329/125289586-07e6ab80-e33d-11eb-80cf-ba7c89efd718.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
