### ISSUE TITLE
User is not able to purchase other Membership plan if an existing Membership Plan is activated

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#26]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Store end --> Membership Plans
Status: new
Version: 1.0.0
Description: The user is not able to see and purchase other Membership Plan if created for same Products and Categories as already purchased plan with more discount, Price and validity.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
