### ISSUE TITLE
Company name is not correctly implemented on plugins page

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#3]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Admin Panel --> Plugins --> Membership For WooCommerce
Status: new
Version: 1.0.0
Description: Company name is not implemented fine it should be **MakeWebBetter** without any space.
![CompanyName-‹-Membership-for-WooCommerce-—-WordPress](https://user-images.githubusercontent.com/76723329/109461283-ebca2800-7a87-11eb-81be-305eca4df512.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/76723329/126320647-fc26cb6c-9ff7-4104-b5cf-bb5740e362bc.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
