### ISSUE TITLE
"Membership Plan Shortcodes" are not working directly as help-tip content is not enough to understand the usage.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#32]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Admin panel --> Plans --> Shortcodes
Status: new
Version: 1.0.0
Description: The Membership Plan Shortcodes help-tip content is not enough to understand the usage of shortcodes. As of now they can'nt be used directly. Please provide more info for admin to use the short codes.

**Comment by ChiragGupta-CEDCOSS** [comment]
Shortcode is not working.
![Screenshot (16)](https://user-images.githubusercontent.com/76723329/126432461-38993547-870e-45ef-adc9-1fbc0915b7a3.png)
![Screenshot (17)](https://user-images.githubusercontent.com/76723329/126432475-8159b0b1-6ae3-49e6-9c33-a9615d4bb7da.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
