### ISSUE TITLE
Membership Plan Status should change when When admin Disable Membership Plans from store-end.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#36]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Admin panel --> Plans --> All Plans
Status: new
Version: 1.0.0
Description: The Membership Plan Status should change from **Live** when When admin Disable Membership Plans from store-end using Global Settings.
![Plans-‹-Membership-for-WooCommerce-—-WordPress](https://user-images.githubusercontent.com/76723329/109609466-5e530a80-7b51-11eb-88a7-cdb7cad0f07e.png)
![Global-Settings-‹-Membership-for-WooCommerce-—-WordPress](https://user-images.githubusercontent.com/76723329/109609551-7cb90600-7b51-11eb-92dc-99697e667b2d.png)

**Comment by Ananya-Cedcoss** [comment]
For now if membership is disabled from general setting than membership plan will also show as disabled from setting

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
