### ISSUE TITLE
Visit plugin site page is not found

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#4]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Admin Panel --> Plugins --> Membership For WooCommerce
Status: new
Version: 1.0.0
Description: **Visit plugin site** link page is not found, after clicking on link.
![Page-not-found-MakeWebBetter](https://user-images.githubusercontent.com/76723329/109461614-6dba5100-7a88-11eb-8841-f1e782e86b80.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Links are not present woth plugin:
![Screenshot (13)](https://user-images.githubusercontent.com/76723329/126321355-0f2fbeaa-34b9-4d09-a7fd-99015ac7d308.png)
![Screenshot (14)](https://user-images.githubusercontent.com/76723329/126321415-2249e9cd-e2b8-4340-882b-e997a225437e.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
