### ISSUE TITLE
Error message is displaying for product selected in any membership plan.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#41]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Store-end
Status: new
Version: 1.0.0
Description: The error message is displaying everytime for product selected in any membership plan when user/ admin login to store-end.
![image](https://user-images.githubusercontent.com/76723329/109938067-9e52f280-7cf5-11eb-866c-2deb872920ba.png)

**Comment by Ananya-Cedcoss** [comment]
Session issue is resolved

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
