### ISSUE TITLE
When membership plan is Deleted permanently by the admin the membership is still active for the user.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#47]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Store end --> Membership Plans
Status: new
Version: 1.0.0
Description: If the admin Delete permanently membership plan, the user is still able to get the membership discount for that plan. Even if no membership plan exists.
![Memberships-‹-MWB_wpbrowser_040221-—-WordPress](https://user-images.githubusercontent.com/76723329/110198950-ff0c3780-7e7b-11eb-9905-df525fa877e8.png)
![Cart-–-MWB_wpbrowser_040221](https://user-images.githubusercontent.com/76723329/110198971-1c410600-7e7c-11eb-8961-7b88fdd473a3.png)
![Edit-Member-‹-MWB_wpbrowser_040221-—-WordPress](https://user-images.githubusercontent.com/76723329/110198989-3bd82e80-7e7c-11eb-8939-37a710ebae6b.png)

**Comment by Ananya-Cedcoss** [comment]
In this case when plan is deleted all pending request from store will be removed . For existing membership user we can manage from member table

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
