### ISSUE TITLE
Move to trash option is not present to implement bulk actions on All Members table.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#48]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Admin panel --> Memberships --> All Members
Status: new
Version: 1.0.0
Description: On All Members table list content the move to trash option is not available for admin to take actions on membership request list.
![Members](https://user-images.githubusercontent.com/76723329/110444394-f5383d80-80e2-11eb-81dd-6fe50cb0bf4c.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Move to trash option is available under Edit membership but not working fine.
![Screenshot (24)](https://user-images.githubusercontent.com/76723329/127282797-84fa6dcc-7f85-4b7a-92f0-63a68f27e11e.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Now option is removed, fine for now.
