### ISSUE TITLE
Advance Direct Bank Transfer payment setup is not working and generating Warning

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#51]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> WooCommerce --> Settings --> Payments --> Advance Direct Bank Transfer
Status: new
Version: 1.0.0
Description: Advance Direct Bank Transfer payment setup is not working and generating Warning.
![Screenshot02](https://user-images.githubusercontent.com/76723329/113394079-428f8e00-93b5-11eb-9719-897d7f93fb27.png)

**Comment by brijmohan-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
