### ISSUE TITLE
Membership Details are not visible at Store-end

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#52]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Store-end --> My account --> Membership Details --> View
Status: new
Version: 1.0.0
Description: When user is purchasing plan Membership Details are not visible at Store-end.
![Screenshot (14)](https://user-images.githubusercontent.com/76723329/113407221-7e811e00-93ca-11eb-8bc8-22826a3c9965.png)

**Comment by brijmohan-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
