### ISSUE TITLE
Plugin name should be Membership For WooCommerce

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#53]
WordPress version: 5.6.2
WooCommerce version: 5.0.0
Area Path: Admin panel --> Plugins --> Membership For Woocommerce
Status: new
Version: 1.0.0
Description: Plugin name should be Membership For WooCommerce

**Comment by brijmohan-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
