### ISSUE TITLE
Getting notice from WP version 5.7

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#54]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> Memberships
Status: new
Version: 1.0.0
Description: Getting Notice from WP version 5.7
![Screenshot01](https://user-images.githubusercontent.com/76723329/113414668-2c94c400-93db-11eb-87f8-0ec580be0c59.png)

**Comment by brijmohan-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
![Screenshot (89)](https://user-images.githubusercontent.com/76723329/125296457-f228b480-e343-11eb-86b8-82620903d594.png)

**Comment by Ananya-Cedcoss** [comment]
Not getting this notice now
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
