### ISSUE TITLE
User is able to send multiple requests and no Under review status is available on Membership products

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#55]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Store-end --> Shop --> Membership
Status: new
Version: 1.0.0
Description: User is able to send multiple requests and no Under review status is available on Membership products, after the earlier request is set to Pending Status.
![Screenshot (14)](https://user-images.githubusercontent.com/76723329/113470303-36b5d180-9472-11eb-8125-a0d861e35179.png)
![Screenshot (15)](https://user-images.githubusercontent.com/76723329/113470309-41706680-9472-11eb-8647-43502dd4af6d.png)
![Screenshot (16)](https://user-images.githubusercontent.com/76723329/113470314-53eaa000-9472-11eb-96e5-a1b7e59b5ce4.png)

**Comment by brijmohan-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still not fixed.

**Comment by brijmohan-cedcoss** [comment]
Let me explain you this, pending status are for those members who by any reason did not able to reach the payment process, and if a member completes the payment either via Advance bacs or Paypal and his/her payment is not refelected in the owners account then for that purpose we are having its status as On-hold.

And as per your query, we will give the option to either delete or expire a membership in the pro version.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
