### ISSUE TITLE
Expiry Date is not available for requests on admin panel

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#56]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> Memberships --> All Members
Status: new
Version: 1.0.0
Description: Expiry Date is not available for requests on admin panel after the earlier request is set to Pending Status.
![Screenshot (17)](https://user-images.githubusercontent.com/76723329/113470397-df643100-9472-11eb-924b-ad17b1cb281c.png)

**Comment by brijmohan-cedcoss** [comment]
Incase of Advance bank transfer -> Expiry date will only be display if we first complete the membership manually,
Incase of paypal -> It will be calculated at the instant when the payment gets completed

**Comment by ChiragGupta-CEDCOSS** [comment]
Ok
