### ISSUE TITLE
Error message is coming on membership purchase form

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#57]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Store-end --> Shop --> Membership --> Buy Now!
Status: new
Version: 1.0.0
Description: Error message is coming on membership purchase form as- Please enter a valid email.
![screen07](https://user-images.githubusercontent.com/76723329/113470492-b6906b80-9473-11eb-974c-65f6becf3840.jpg)

**Comment by brijmohan-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still error message is displaying without giving any input(when the form gets open first time).
![Screenshot (18)](https://user-images.githubusercontent.com/76723329/113537837-5fb39f00-95f7-11eb-9577-3f2b12d0e910.png)

**Comment by Ananya-Cedcoss** [comment]
this form is no more present in the project
