### ISSUE TITLE
Replace Skype support link from Ticket Support link on overview page.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#58]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Admin panel --> Memberships --> Overview
Status: new
Version: 1.0.0
Description: The Skype support link should be replaced from Ticket Support link on the overview page.
![Screenshot (19)](https://user-images.githubusercontent.com/76723329/113549697-7a920d80-960f-11eb-8fad-0136baeb25d2.png)

**Comment by brijmohan-cedcoss** [comment]
Before raising any issue consult it with your seniors, I have asked it about this with Anjali Ma'am and she said its fine no need to change it.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
