### ISSUE TITLE
QA and Grammatical issues

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#59]
WordPress version: 5.7
WooCommerce version: 5.1.0
Plugin name: Membership For WooCommerce

phpcs: 
[membership-for-woocommerce.docx](https://github.com/Makewebbetter/membership-for-woocommerce/files/6301567/membership-for-woocommerce.docx)

QA and Grammatical: 
[Membership QA and Grammatical issues.docx](https://github.com/Makewebbetter/membership-for-woocommerce/files/6301570/Membership.QA.and.Grammatical.issues.docx)

**Comment by brijmohan-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Plugin name: Membership For WooCommerce
Version: 1.1.0

phpcs issues:
[membership-for-woocommerce.txt](https://github.com/Makewebbetter/membership-for-woocommerce/files/7004489/membership-for-woocommerce.txt)


QA issues:
[membership-for-woocommerce QA issues.txt](https://github.com/Makewebbetter/membership-for-woocommerce/files/7004486/membership-for-woocommerce.QA.issues.txt)

**Comment by Ananya-Cedcoss** [comment]
Use placeholders and $wpdb->prepare(); found $query this can not be resolved as creating issue in plugin

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
