### ISSUE TITLE
Admin is not able to change the status of Membership Request.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#60]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> Memberships --> All Members --> Edit
Status: new
Version: 1.0.0
Description: Admin is not able to change the status of the Membership Request. Getting Fatal error.
![Screenshot (40)](https://user-images.githubusercontent.com/76723329/120634356-c71b8d00-c488-11eb-9fe1-14fe1b866daf.png)

![Screenshot (38)](https://user-images.githubusercontent.com/76723329/120634243-a7846480-c488-11eb-9480-5b44e796c25f.png)

**Comment by mohddaniyal-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
