### ISSUE TITLE
Export/ Import Plans are not working fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#61]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> Memberships --> All membership Plans
Status: new
Version: 1.0.0
Description: Export/ Import Plans are not working fine. When we export one plan and then import plan from that csv file 3 plans are getting imported.
![Screenshot (47)](https://user-images.githubusercontent.com/76723329/120647765-94799080-c498-11eb-8e62-d325a099fc09.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
An empty file is getting exported while the plan already existed.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
