### ISSUE TITLE
Overview content is not updated.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#62]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> Plugins --> WooCommerce Membership
Status: new
Version: 1.0.0
Description: Overview content is not updated.
![Screenshot (48)](https://user-images.githubusercontent.com/76723329/120650984-e8d23f80-c49b-11eb-8dd4-448da02ee53b.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
![Screenshot (25)](https://user-images.githubusercontent.com/76723329/127290097-9d8fea11-c903-40c4-a32d-5a1cd77e924f.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
