### ISSUE TITLE
Attach Invoice to Email feature is not working.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#63]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> Memberships --> Global Settings
Status: new
Version: 1.0.0
Description: Attach Invoice to Email feature is not working.
![Screenshot (96)](https://user-images.githubusercontent.com/76723329/121341837-af3b8180-c93e-11eb-911f-e390edb1ed82.png)
![Screenshot (97)](https://user-images.githubusercontent.com/76723329/121341939-caa68c80-c93e-11eb-981e-b4d0048d0bc1.png)

**Comment by Ananya-Cedcoss** [comment]
pro feature

**Comment by ChiragGupta-CEDCOSS** [comment]
In this case this feature shouldn't appear/ work in org plugin.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still not fixed.

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
