### ISSUE TITLE
Membership plan is not getting expired.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#64]
WordPress version: 5.7.2
WooCommerce version: 5.4.1
Area Path: Admin panel --> Memberships --> All Members
Version: 1.1.0
Description: Membership plan is not getting expired and the user is able to get membership discount after expiry date.
![Screenshot (9)](https://user-images.githubusercontent.com/76723329/123105403-695ddd80-d455-11eb-831f-f326e8cc26f2.png)
![Screenshot (8)](https://user-images.githubusercontent.com/76723329/123105287-4e8b6900-d455-11eb-896d-f4ffc262058d.png)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
