### ISSUE TITLE
Plan details are not coming fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#65]
WordPress version: 5.7.2
WooCommerce version: 5.4.1
Area Path: Store --> My account --> Membership Details
Version: 1.1.0
Description: Plan details are not coming fine at store.
![Screenshot (10)](https://user-images.githubusercontent.com/76723329/123114523-02dcbd80-d45d-11eb-833e-6eac932f5338.png)

**Comment by Ananya-Cedcoss** [comment]
now coming fine

**Comment by Ananya-Cedcoss** [comment]
![Uploading Screenshot from 2021-07-05 18-17-23.png…]()

**Comment by Ananya-Cedcoss** [comment]
![Screenshot from 2021-07-05 18-17-23](https://user-images.githubusercontent.com/79438168/124474984-d01cb880-ddbe-11eb-9b00-fb553aea0ee3.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Still need to be improved.
![screenshot-localhost-10013-2021-07-10-12-57-07-238](https://user-images.githubusercontent.com/76723329/125155564-83e6c500-e17e-11eb-809d-540cca6d3a1d.png)

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/125969771-25280010-3618-4cc6-9ab7-91503e838e00.png)
solved

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Offered products are not visible. Extra content is visible.
![Screenshot(10)](https://user-images.githubusercontent.com/76723329/127280396-2a0940bb-10df-4718-b452-838bd6b309ac.png)
![Screenshot (23)](https://user-images.githubusercontent.com/76723329/127280585-7d74bdb4-a39e-4026-aaba-8c11720a8fa8.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
The issue is coming again.
![screenshot-localhost-10044-2021-09-13-15-51-19-306](https://user-images.githubusercontent.com/76723329/133067532-3892c75c-04a8-41ad-ae48-774b108766ac.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
