### ISSUE TITLE
Other Available Membership plans UI is not coming fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#67]
WordPress version: 5.7.2
WooCommerce version: 5.4.1
Area Path: Store
Version: 1.1.0
Description: Other Available Membership plans UI is not coming fine. Membership details are also not coming fine.
![Screenshot(6)](https://user-images.githubusercontent.com/76723329/125299903-31a4d000-e347-11eb-8b71-b57b193ee57c.png)

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/125969848-417718d0-fc15-4ced-8f24-0497fccb2fe1.png)
solved

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
