### ISSUE TITLE
Feature content is not updated

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#68]
WordPress version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel -> MakeWebBetter -> Membership For WooCommerce
Version: 1.1.0
Description: Show History to User feature description is not correct & Email Subject field placeholder text is not correct.
![Screenshot (15)](https://user-images.githubusercontent.com/76723329/126324004-4d11a29e-b799-4b7b-9e39-2166ee1539b8.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
