### ISSUE TITLE
Membership shipping is not getting applied.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#69]
WordPress version: 5.8
WooCommerce version: 5.5.2
Area Path: Store
Version: 1.1.0
Description: Membership shipping is not getting applied.
![Screenshot(7)](https://user-images.githubusercontent.com/76723329/127265759-b8e6cece-ea60-4cac-be97-7c04b3f330e3.png)
![Screenshot (22)](https://user-images.githubusercontent.com/76723329/127265771-81107a9d-5960-45cf-ad80-97c026161f6b.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
