### ISSUE TITLE
General setting are not working fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#71]
WordPress version: 5.8
WooCommerce version: 5.5.2
Area Path: Admin panel -> MakeWebBetter -> Membership For WooCommerce --> General Setting
Version: 1.1.0
Description: General settings are not working fine.
![Screenshot (28)](https://user-images.githubusercontent.com/76723329/127324524-3a830ec0-4501-476a-9b68-9c86ae59d78f.png)
![Screenshot (30)](https://user-images.githubusercontent.com/76723329/127324604-ec688188-9317-4f1a-9f0a-3e89f6844359.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
