### ISSUE TITLE
View Membership plan link is not correct.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#72]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Admin panel-> Memberships-> All Membership plans-> Edit
Status: new
Version: 1.1.1
Description: View Membership plan link is not correct.
![Screenshot (35)](https://user-images.githubusercontent.com/76723329/132353666-e4f4bd14-6aaa-4208-ba73-93f5dadb5b96.png)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Now the link is removed. Fine for now.
