### ISSUE TITLE
Membership plans page details are not coming fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#73]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Store-> Membership plans
Status: new
Version: 1.1.1
Description: Membership plans page details are not coming fine. As of now, membership details are not coming for guest users and if the Membership plan name is changed it is not reflecting on the front end for users other than guest users.
->UI can be improved for better listing of Membership plans at the store.
![Screenshot (36)](https://user-images.githubusercontent.com/76723329/132357157-5afeb2e7-b22c-43e5-bdf1-51c6ff6da143.png)
![Screenshot (37)](https://user-images.githubusercontent.com/76723329/132357179-e05e4e3e-10b0-4149-a6f2-e6a245245c7c.png)

->Buttons font size is different
![Screenshot (38)](https://user-images.githubusercontent.com/76723329/132448876-7cfbbf18-a369-404f-b8fd-73e7702832a5.png)

-> If all plans are purchased blank page is visible
![Screenshot(2)](https://user-images.githubusercontent.com/76723329/132465184-3ed8349f-912d-4608-9ed4-8ed469d0e6aa.png)

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/133385809-7298578e-bacc-45a5-8b0c-ed82901e420a.png)
![image](https://user-images.githubusercontent.com/79319224/133386959-69aeca92-2590-4a01-b0ce-95347e53c5c2.png)

solved

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.

**Comment by Ananya-Cedcoss** [comment]
bug is fixed now

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/134338963-30581ff5-ca06-4ebb-9e52-70c106930371.png)
fixed seperation of plan issue

**Comment by ChiragGupta-CEDCOSS** [comment]
For guest users still, Membership plans page is not accessible.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
