### ISSUE TITLE
Manage Free Membership button is not appearing when Free Shipping is enabled.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#74]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Admin panel-> Memberships-> All Membership plans
Status: new
Version: 1.1.1
Description: Manage Free Membership button is not appearing when Free Shipping is enabled.
![Screenshot (39)](https://user-images.githubusercontent.com/76723329/132460836-711f065d-94ec-4fa3-bd3c-94e5082b780f.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
