### ISSUE TITLE
PHP Errors

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/membership-for-woocommerce#75]
**Bug Name -** PHP Errors
**Area Path -** 
**Status -** Compatibility with Wishlist
**Woo Commerce Version -** 5.6.0
**WordPress Version -** 5.8.1
**Plugin Version -** 1.0.0
**Description -**

when we go to read more of membership products from wishlist.

![image](https://user-images.githubusercontent.com/76723393/132994726-10e8d5b5-2e9f-4272-a2f8-5724b7f2b28a.png)

![image](https://user-images.githubusercontent.com/76723393/132994757-8efda8fb-dad3-46b7-83bd-b6de156db07b.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
