### ISSUE TITLE
Activating plugin without WooCommerce on multisite error message issue.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#76]
WordPress version: 5.8.1
WooCommerce version: 5.6.0
Compatible: Multisite
Area Path: Admin panel -> Plugins
Version: 1.2.0
Description: When we activate the plugin without WooCommerce no error message is coming.
![Screenshot - 2021-09-14T101919 742](https://user-images.githubusercontent.com/76723329/133197202-ccb2accd-2148-4a60-8dd5-2fc1c785d780.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
