### ISSUE TITLE
Products having tag are visible as membership products.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#78]
WordPress version: 5.8.1
WooCommerce version: 5.6.0
Area Path: Shop
Version: 1.2.0
Description: Products having tags are visible as membership products while they are not included in any plan.
![Screenshot - 2021-09-17T190333 346](https://user-images.githubusercontent.com/76723329/133791204-b9dd7631-b2c9-4683-a845-d5eded7bbabf.png)
![Screenshot - 2021-09-17T190257 076](https://user-images.githubusercontent.com/76723329/133791235-e2d21d0c-8381-46db-b104-b9babd3d1655.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
