### ISSUE TITLE
Membership status of members is not coming fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#79]
WordPress version: 5.8.1
WooCommerce version: 5.6.0
Area Path: Admin panel -> Memberships-> All Members
Version: 1.2.0
Description: The membership status of members is not coming fine. As of now Membership in pending status is getting expired also Expiry Date is not coming fine for pending membership.
![Screenshot - 2021-09-17T191636 589](https://user-images.githubusercontent.com/76723329/133793212-66e0eb47-5d42-4d54-9f1c-9b78a808fc66.png)
![Screenshot - 2021-09-17T193338 554](https://user-images.githubusercontent.com/76723329/133795862-0e8e69a6-54f3-46b3-bc89-35d8fc2b3b0a.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.
![Screenshot - 2021-09-24T104419 392](https://user-images.githubusercontent.com/76723329/134621879-952a79e2-20cc-43cc-bede-fdbad8bae4de.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
