### ISSUE TITLE
Membership plan can't be purchased.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#80]
WordPress version: 5.8.1
WooCommerce version: 5.6.0
Compatible: Multisite
Area Path: Shop
Version: 1.2.0
Description: Membership plans can't be purchased, when the user clicks on the plan to purchase user getting redirected back to the product page. Also getting errors with the product.
![Screenshot - 2021-09-19T163002 518](https://user-images.githubusercontent.com/76723329/133925214-350260fd-2179-402b-9f5d-6a518a7e4d5d.png)

**Comment by Ananya-Cedcoss** [comment]
Not getting the exact error but solved the undefined variable link error

**Comment by ChiragGupta-CEDCOSS** [comment]
Still not fixed.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Now getting error at cart.
![Screenshot - 2021-09-27T175547 973](https://user-images.githubusercontent.com/76723329/134907567-7e5f733f-512e-4841-a594-586e8ca57b8c.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
