### ISSUE TITLE
Getting error while creating new site.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#81]
WordPress version: 5.8.1
WooCommerce version: 5.6.0
Compatible: Multisite
Area Path: Admin panel
Version: 1.2.0
Description: Getting error while creating the new site.
![Screenshot - 2021-09-19T163924 604](https://user-images.githubusercontent.com/76723329/133925368-ac947a5f-573d-4c8c-aca2-ce75d1937638.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
