### ISSUE TITLE
Getting error with plugin after activating membership plan.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#82]
WordPress version: 5.8.1
WooCommerce version: 5.6.0
Compatible: Multisite
Area Path: Shop
Version: 1.2.0
Description: Getting error with plugin after activating membership plan.
![Screenshot - 2021-09-19T170401 327](https://user-images.githubusercontent.com/76723329/133925950-1d7fded3-54e1-4b5d-a9c4-c5eb2e34d900.png)
![Screenshot - 2021-09-19T170758 032](https://user-images.githubusercontent.com/76723329/133926060-f2b9e26f-c719-4663-b47f-38b296be219f.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.
![Screenshot - 2021-09-23T170436 309](https://user-images.githubusercontent.com/76723329/134500055-11fa04eb-9a7e-4bb2-ace0-114984277028.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
