### ISSUE TITLE
Video is not visible correctly on overview page.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#83]
WordPress version: 5.8.1
WooCommerce version: 5.6.0
Area Path: Admin panel-> MakeWebBetter-> Membership For WooCommerce-> Overview
Version: 1.2.0
Description: Video is not visible correctly on the overview page.
![Screenshot - 2021-09-20T104330 268](https://user-images.githubusercontent.com/76723329/133959521-4e0ac368-e08a-41fb-93b7-27dbe6779e29.png)

**Comment by anmolui** [comment]
![image](https://user-images.githubusercontent.com/79319224/134334457-12fad24a-87a5-494c-a949-53690c6006be.png)
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
