### ISSUE TITLE
Getting error with plugin after adding membership plan to cart.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#84]
WordPress version: 5.8.1
WooCommerce version: 5.7.0
Compatible: MWB Multi Currency Switcher For WooCommerce
Area Path: Shop
Version: 1.2.0
Description: Getting error with plugin after adding membership plan to cart.
![Screenshot from 2021-09-23 16-31-11](https://user-images.githubusercontent.com/76723329/134497271-12e6d04a-8ff0-42bd-aeeb-479781397b0a.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
