### ISSUE TITLE
Membership plans page & Membership product is not creating at new site.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#85]
WordPress version: 5.8.1
WooCommerce version: 5.7.0
Compatible: Multisite
Area Path: Shop
Version: 1.2.0
Description: Membership plans page & Membership product is not getting created at the new site.
![Screenshot - 2021-09-23T171931 893](https://user-images.githubusercontent.com/76723329/134501884-f3fd06cc-1155-4a78-80ba-58f8cc26ed08.png)
![Screenshot - 2021-09-23T171950 709](https://user-images.githubusercontent.com/76723329/134501906-f71da70e-fb75-4fe5-9bbb-b9ec7212dd76.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
