### ISSUE TITLE
Getting error after activating the plugin

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#86]
WordPress version: 5.8.1
WooCommerce version: 5.7.0
Area Path: Admin panel-> Plugins
Version: 1.2.0
Description: Getting error after activating the plugin
![Screenshot - 2021-09-23T095330 705](https://user-images.githubusercontent.com/76723329/134502588-ac863985-357c-4388-998a-1f77478f5472.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
