### ISSUE TITLE
QA/PHPcs Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/membership-for-woocommerce#87]
DOC :
https://docs.google.com/document/d/1zB2UqqCrzosSU907J0xgIzyw1JLdWedefswuz16Bt3E/edit?usp=sharing

File;
[membership-for-woocommerce.xml.zip](https://github.com/Makewebbetter/membership-for-woocommerce/files/7259694/membership-for-woocommerce.xml.zip)

**Comment by Ananya-Cedcoss** [comment]
Use placeholders and $wpdb->prepare(); found $query

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Version: 2.0.0

phpcs issues:
[membership-for-woocommerce.txt](https://github.com/Makewebbetter/membership-for-woocommerce/files/7467105/membership-for-woocommerce.txt)

QA issues:
[membership-for-woocommerce QA issues.txt](https://github.com/Makewebbetter/membership-for-woocommerce/files/7467109/membership-for-woocommerce.QA.issues.txt)

**Comment by Ananya-Cedcoss** [comment]
Use placeholders and $wpdb->prepare(); found $query still not resolved
can not remove style in file as part of boiler plate

**Comment by ChiragGupta-CEDCOSS** [comment]
Fine for now.

**Comment by ChiragGupta-CEDCOSS** [comment]
**Version: 2.0.1**

**QA issues:**
[membership-for-woocommerce QA issues.txt](https://github.com/Makewebbetter/membership-for-woocommerce/files/7653333/membership-for-woocommerce.QA.issues.txt)
