### ISSUE TITLE
Design issue in Membership Plans page.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#91]
WordPress version: 5.8.1
WooCommerce version: 5.8.0
Area Path: Store-> Membership Plans
Version: 2.0.0
Description: Design issue in Membership Plans page with different browsers and themes.
**Browser: Chrome**
![Screenshot (76)](https://user-images.githubusercontent.com/76723329/138403184-94f729be-9bbc-4268-b94c-2da1ad255d49.png)
**Browser: Firefox**
![Screenshot(7)](https://user-images.githubusercontent.com/76723329/138414719-6ff1a59d-50e9-40e0-9992-6f77ce591a61.png)
![Screenshot (85)](https://user-images.githubusercontent.com/76723329/138547148-63ce6358-72f5-49c3-b06e-f703f88243b1.png)
![Screenshot (86)](https://user-images.githubusercontent.com/76723329/138547160-e77a835c-7b50-406b-99ae-ff7c103c41fd.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.
![Screenshot - 2021-10-30T132946 063](https://user-images.githubusercontent.com/76723329/139525252-223c9a21-1702-403c-8d98-7eb5162f7340.png)
![Screenshot - 2021-10-30T133008 448](https://user-images.githubusercontent.com/76723329/139525263-6c3f27e4-32c0-40a6-9545-9de8f3a437c9.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left. 
BeTheme(responsive):
![Screenshot - 2021-10-30T190222 374](https://user-images.githubusercontent.com/76723329/139534714-6c0f5717-fbe7-4227-b3e6-9c4de4d4c17c.png)

**Comment by Ananya-Cedcoss** [comment]
Issues fixed by anmol

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
