### ISSUE TITLE
Membership Shipping is available for Non-Members

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/membership-for-woocommerce#92]
WordPress version: 5.8.1
WooCommerce version: 5.8.0
Area Path: Store-> Cart
Version: 2.0.0
Description: Membership Shipping is available for Non-Members & with plans where Membership shipping is not enabled.
![Screenshot (77)](https://user-images.githubusercontent.com/76723329/138411524-62ea922c-1cab-4e3a-b8f5-3a7d81868827.png)
![Screenshot (78)](https://user-images.githubusercontent.com/76723329/138411543-3d9aaed5-2b91-456d-b6b9-7b2a99e758cd.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Issue coming again.
![Screenshot (58)](https://user-images.githubusercontent.com/76723329/144064702-50d6ccf9-0ee8-413a-860f-5986085b901b.png)
![screenshot-membership-testing local-2021-11-30-19-52-26-343](https://user-images.githubusercontent.com/76723329/144064732-398fee3f-90a5-419e-b980-1b7445ef8c22.png)

**Comment by Ananya-Cedcoss** [comment]
not getting the issue by my side

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
